// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnOAugvyfvzDS3hpQdXgeemRED-rrXZ7Q',
    appId: '1:127865341173:web:070d6d27b6f8b8f59c71bc',
    messagingSenderId: '127865341173',
    projectId: 'my-5056-signal',
    authDomain: 'my-5056-signal.firebaseapp.com',
    storageBucket: 'my-5056-signal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAFZMPWIgMqZhs_-P1O0KijRzrkVH-0Vc',
    appId: '1:127865341173:android:ba254cc27c62f9919c71bc',
    messagingSenderId: '127865341173',
    projectId: 'my-5056-signal',
    storageBucket: 'my-5056-signal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpxayrLbFab11u1DuYH5gr_t-R79LGQk0',
    appId: '1:127865341173:ios:1193d2609e2844a49c71bc',
    messagingSenderId: '127865341173',
    projectId: 'my-5056-signal',
    storageBucket: 'my-5056-signal.appspot.com',
    iosBundleId: 'com.example.oneSignalGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpxayrLbFab11u1DuYH5gr_t-R79LGQk0',
    appId: '1:127865341173:ios:1193d2609e2844a49c71bc',
    messagingSenderId: '127865341173',
    projectId: 'my-5056-signal',
    storageBucket: 'my-5056-signal.appspot.com',
    iosBundleId: 'com.example.oneSignalGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnOAugvyfvzDS3hpQdXgeemRED-rrXZ7Q',
    appId: '1:127865341173:web:b2bba4078b8145e19c71bc',
    messagingSenderId: '127865341173',
    projectId: 'my-5056-signal',
    authDomain: 'my-5056-signal.firebaseapp.com',
    storageBucket: 'my-5056-signal.appspot.com',
  );

}